-- Client-controlled catalogs.
--
-- These values come from the client's workbook.
-- They are NOT generated by the LLM and are NOT replaced by
-- SEOnt / ICASA / Crop Ontology.

CREATE TABLE IF NOT EXISTS client_catalog (
    catalog_id      VARCHAR(100) PRIMARY KEY,
    name            VARCHAR(300) NOT NULL DEFAULT '',
    description     TEXT NOT NULL DEFAULT '',
    version         VARCHAR(100) NOT NULL DEFAULT '',
    status          VARCHAR(50) NOT NULL DEFAULT '',
    source          TEXT NOT NULL DEFAULT '',
    imported_on     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS client_catalog_value (
    value_id        BIGSERIAL PRIMARY KEY,

    catalog_id      VARCHAR(100) NOT NULL
                    REFERENCES client_catalog(catalog_id)
                    ON DELETE CASCADE,

    code            VARCHAR(200) NOT NULL,
    label           VARCHAR(500) NOT NULL DEFAULT '',
    definition      TEXT NOT NULL DEFAULT '',

    -- Important for CIMMYT Father/Parent List relationships.
    parent_code     VARCHAR(200),

    display_order   INTEGER NOT NULL DEFAULT 10000,
    status          VARCHAR(50) NOT NULL DEFAULT '',

    valid_from      VARCHAR(100) NOT NULL DEFAULT '',
    valid_to        VARCHAR(100) NOT NULL DEFAULT '',

    imported_on     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_on      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (catalog_id, code)
);

CREATE INDEX IF NOT EXISTS idx_client_catalog_value_catalog
    ON client_catalog_value(catalog_id);

CREATE INDEX IF NOT EXISTS idx_client_catalog_value_parent
    ON client_catalog_value(catalog_id, parent_code);

CREATE INDEX IF NOT EXISTS idx_client_catalog_name
    ON client_catalog(lower(name));
-- Added after the first release; app/modules/client_catalog/bootstrap.py adds
-- them to databases that already had the table.

-- Who made the catalogue, when it was built here rather than imported.
ALTER TABLE client_catalog
    ADD COLUMN IF NOT EXISTS created_by VARCHAR(200) NOT NULL DEFAULT '';

-- The catalogue this one's values hang off, for a dependent list: a district
-- catalogue names the state catalogue, and every district's parent_code must be
-- a code in it. Stored, never inferred.
ALTER TABLE client_catalog
    ADD COLUMN IF NOT EXISTS parent_catalog_id VARCHAR(100)
        REFERENCES client_catalog(catalog_id) ON DELETE SET NULL;
