import React, { useMemo } from "react";
import Highcharts from "highcharts";
import HighchartsReact from "highcharts-react-official";

import { widgetColors } from "./colors.js";
import { useChartFit } from "./useChartFit.js";

export default function HighchartHistogramRenderer({ widget, data, dashboard }) {
  // Sized and resized by its container, not by a 400px default.
  const chartRef = useChartFit();

  const options = useMemo(() => {
    const p = widget.presentation || {};
    
    const fieldName = widget.histogram?.field;
    const requestedBins = widget.histogram?.bins || 10;
    
    // The alias generated by query_builder for aggregation="NONE"
    const alias = `${fieldName}_none`;

    // 1. Extract valid numeric data
    const validValues = [];
    if (data && data.length > 0) {
      for (const row of data) {
        const val = row[alias];
        if (val !== null && val !== undefined) {
          const num = Number(val);
          if (!isNaN(num) && isFinite(num)) {
            validValues.push(num);
          }
        }
      }
    }

    let binWidth = 1;
    let minVal = 0;
    let maxVal = 0;
    let bins = [];
    let categories = [];
    let seriesData = [];

    if (validValues.length > 0) {
      minVal = Math.min(...validValues);
      maxVal = Math.max(...validValues);

      if (minVal === maxVal) {
        // Handle min === max case
        binWidth = 1;
        categories = [`${minVal}`];
        seriesData = [validValues.length];
      } else {
        // Handle normal binning
        const numBins = Math.max(1, requestedBins);
        binWidth = (maxVal - minVal) / numBins;

        // Initialize bins
        for (let i = 0; i < numBins; i++) {
          bins.push(0);
          
          const binStart = minVal + i * binWidth;
          const binEnd = minVal + (i + 1) * binWidth;
          
          // Format categories to 2 decimal places to avoid long floating point strings
          const startLabel = Number.isInteger(binStart) ? binStart : binStart.toFixed(2);
          const endLabel = Number.isInteger(binEnd) ? binEnd : binEnd.toFixed(2);
          
          categories.push(`${startLabel} - ${endLabel}`);
        }

        // Assign values to bins
        for (const val of validValues) {
          if (val === maxVal) {
            bins[numBins - 1]++;
          } else {
            const binIndex = Math.floor((val - minVal) / binWidth);
            bins[binIndex]++;
          }
        }
        
        seriesData = bins;
      }
    }

    return {
      chart: {
        type: "column",
        backgroundColor: "transparent",
        animation: false,
        // Highcharts keeps 10px around the plot and 15 under it, which is
        // a second margin inside a widget that already has one.
        spacing: [4, 4, 4, 4],
      },
      title: {
        text: null
      },
      credits: {
        enabled: false
      },
      legend: {
        enabled: false
      },
      xAxis: {
        categories: categories,
        title: {
          text: p.x_axis?.title || fieldName || "",
          style: {
            fontSize: p.x_axis?.font_size ? `${p.x_axis.font_size}px` : undefined,
            fontWeight: p.x_axis?.bold ? "bold" : "normal",
            fontStyle: p.x_axis?.italic ? "italic" : "normal"
          }
        }
      },
      yAxis: {
        title: {
          text: p.y_axis?.title || "Count",
          style: {
            fontSize: p.y_axis?.font_size ? `${p.y_axis.font_size}px` : undefined,
            fontWeight: p.y_axis?.bold ? "bold" : "normal",
            fontStyle: p.y_axis?.italic ? "italic" : "normal"
          }
        }
      },
      plotOptions: {
        column: {
          pointPadding: 0,
          borderWidth: 1,
          groupPadding: 0,
          shadow: false
        }
      },
      series: [
        {
          name: "Frequency",
          color: widgetColors(widget, dashboard).series || undefined,
          data: seriesData
        }
      ]
    };
  }, [widget, data, dashboard]);

  return (
    <div className="dash__chart-fill">
      <HighchartsReact
        ref={chartRef}
        highcharts={Highcharts}
        options={options}
        containerProps={{ className: "dash__chart-fill" }}
      />
    </div>
  );
}
